In [1]:
import pandas as pd

In [2]:
e = pd.DataFrame({
    "Name": ["Arun", "Rahul", "Amit", "Sneha", "Priya", "Karan", "Riya", "Arun"],
    "Age": [23, 28, 35, 30, 27, 40, 26, 23],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT", "IT"],
    "Salary": [40000, 50000, 70000, 65000, 48000, 80000, 42000, 45000]
})
e

    Name  Age Department  Salary
0   Arun   23         IT   40000
1  Rahul   28         HR   50000
2   Amit   35         IT   70000
3  Sneha   30    Finance   65000
4  Priya   27         HR   48000
5  Karan   40    Finance   80000
6   Riya   26         IT   42000
7   Arun   23         IT   45000

In [3]:
d = pd.DataFrame({
    "Department": ["IT", "HR", "Finance"],
    "Manager": ["Rajesh", "Suman", "Anita"]
})

d

  Department Manager
0         IT  Rajesh
1         HR   Suman
2    Finance   Anita

In [4]:
s = pd.DataFrame({
    "Date": [
        "2023-01-10", "2023-01-15", "2023-02-10", "2023-02-18",
        "2023-03-05", "2023-03-20", "2023-04-12", "2023-04-25"
    ],
    "Region": ["West", "East", "West", "North", "West", "East", "South", "West"],
    "Product": ["Laptop", "Mobile", "Laptop", "Tablet", "Mobile", "Laptop", "Tablet", "Laptop"],
    "Sales": [5000, 3000, 7000, 2000, 6000, 8000, 4000, 9000]
})

s

         Date Region Product  Sales
0  2023-01-10   West  Laptop   5000
1  2023-01-15   East  Mobile   3000
2  2023-02-10   West  Laptop   7000
3  2023-02-18  North  Tablet   2000
4  2023-03-05   West  Mobile   6000
5  2023-03-20   East  Laptop   8000
6  2023-04-12  South  Tablet   4000
7  2023-04-25   West  Laptop   9000

In [5]:
print(e.query('Age>25'))

    Name  Age Department  Salary
1  Rahul   28         HR   50000
2   Amit   35         IT   70000
3  Sneha   30    Finance   65000
4  Priya   27         HR   48000
5  Karan   40    Finance   80000
6   Riya   26         IT   42000

In [6]:
avg_sal=e.groupby('Salary')

In [7]:
avg_sal=e['Salary'].mean()
avg_sal

np.float64(55000.0)

In [8]:
print(e[e['Salary']>avg_sal])

    Name  Age Department  Salary
2   Amit   35         IT   70000
3  Sneha   30    Finance   65000
5  Karan   40    Finance   80000

In [9]:
e=e.drop_duplicates('Name')

In [10]:
e

    Name  Age Department  Salary
0   Arun   23         IT   40000
1  Rahul   28         HR   50000
2   Amit   35         IT   70000
3  Sneha   30    Finance   65000
4  Priya   27         HR   48000
5  Karan   40    Finance   80000
6   Riya   26         IT   42000

In [11]:
e['Sal_cat']=e['Salary'].apply(lambda x: 'high' if x>50000 else 'low')

C:\Users\goswa\AppData\Local\Temp\ipykernel_6776\2822566797.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  e['Sal_cat']=e['Salary'].apply(lambda x: 'high' if x>50000 else 'low')

In [12]:
e

    Name  Age Department  Salary Sal_cat
0   Arun   23         IT   40000     low
1  Rahul   28         HR   50000     low
2   Amit   35         IT   70000    high
3  Sneha   30    Finance   65000    high
4  Priya   27         HR   48000     low
5  Karan   40    Finance   80000    high
6   Riya   26         IT   42000     low

In [13]:
ed=pd.merge(e,d, on="Department")

In [14]:
ed

    Name  Age Department  Salary Sal_cat Manager
0   Arun   23         IT   40000     low  Rajesh
1  Rahul   28         HR   50000     low   Suman
2   Amit   35         IT   70000    high  Rajesh
3  Sneha   30    Finance   65000    high   Anita
4  Priya   27         HR   48000     low   Suman
5  Karan   40    Finance   80000    high   Anita
6   Riya   26         IT   42000     low  Rajesh

In [15]:
ed['Salary']=ed['Salary'].astype(float)

In [16]:
ed

    Name  Age Department   Salary Sal_cat Manager
0   Arun   23         IT  40000.0     low  Rajesh
1  Rahul   28         HR  50000.0     low   Suman
2   Amit   35         IT  70000.0    high  Rajesh
3  Sneha   30    Finance  65000.0    high   Anita
4  Priya   27         HR  48000.0     low   Suman
5  Karan   40    Finance  80000.0    high   Anita
6   Riya   26         IT  42000.0     low  Rajesh

In [17]:
ed['Salary'].mean()

np.float64(56428.57142857143)

In [18]:
s

         Date Region Product  Sales
0  2023-01-10   West  Laptop   5000
1  2023-01-15   East  Mobile   3000
2  2023-02-10   West  Laptop   7000
3  2023-02-18  North  Tablet   2000
4  2023-03-05   West  Mobile   6000
5  2023-03-20   East  Laptop   8000
6  2023-04-12  South  Tablet   4000
7  2023-04-25   West  Laptop   9000

In [19]:
s[(s['Region']=='West') & (s['Sales']>5000)]

         Date Region Product  Sales
2  2023-02-10   West  Laptop   7000
4  2023-03-05   West  Mobile   6000
7  2023-04-25   West  Laptop   9000

In [20]:
group1=s.groupby('Product')

In [21]:
print(group1.mean('Sales'))

          Sales
Product
Laptop   7250.0
Mobile   4500.0
Tablet   3000.0

In [22]:
print(group1.sum('Sales'))

         Sales
Product
Laptop   29000
Mobile    9000
Tablet    6000

In [23]:
print(group1.max('Sales'))

         Sales
Product
Laptop    9000
Mobile    6000
Tablet    4000

In [24]:
ss=group1['Sales'].agg(['sum','mean','max'])
ss

           sum    mean   max
Product
Laptop   29000  7250.0  9000
Mobile    9000  4500.0  6000
Tablet    6000  3000.0  4000

In [25]:
s.pivot_table(index=['Region'],values=['Sales'],columns=['Product'],aggfunc=['sum'])

             sum
           Sales
Product   Laptop  Mobile  Tablet
Region
East      8000.0  3000.0     NaN
North        NaN     NaN  2000.0
South        NaN     NaN  4000.0
West     21000.0  6000.0     NaN

In [26]:
s['Date']=pd.to_datetime(s['Date'], format='mixed', dayfirst=True)  #to format dates

In [27]:
s

        Date Region Product  Sales
0 2023-01-10   West  Laptop   5000
1 2023-01-15   East  Mobile   3000
2 2023-02-10   West  Laptop   7000
3 2023-02-18  North  Tablet   2000
4 2023-03-05   West  Mobile   6000
5 2023-03-20   East  Laptop   8000
6 2023-04-12  South  Tablet   4000
7 2023-04-25   West  Laptop   9000

In [28]:
s.set_index('Date', inplace=True)

In [29]:
s

           Region Product  Sales
Date
2023-01-10   West  Laptop   5000
2023-01-15   East  Mobile   3000
2023-02-10   West  Laptop   7000
2023-02-18  North  Tablet   2000
2023-03-05   West  Mobile   6000
2023-03-20   East  Laptop   8000
2023-04-12  South  Tablet   4000
2023-04-25   West  Laptop   9000

In [30]:
s.resample('ME').sum('Sales')

            Sales
Date
2023-01-31   8000
2023-02-28   9000
2023-03-31  14000
2023-04-30  13000

In [31]:
s.resample('ME').sum('Sales').max()

Sales    14000
dtype: int64

In [32]:
e.loc[4,'Salary']=250000

In [33]:
e

    Name  Age Department  Salary Sal_cat
0   Arun   23         IT   40000     low
1  Rahul   28         HR   50000     low
2   Amit   35         IT   70000    high
3  Sneha   30    Finance   65000    high
4  Priya   27         HR  250000     low
5  Karan   40    Finance   80000    high
6   Riya   26         IT   42000     low

In [34]:
#Outliers
mean=e['Salary'].mean()
std=e['Salary'].std()

In [35]:
print(e[e['Salary']<mean-2*std])  #lowest outliers

Empty DataFrame
Columns: [Name, Age, Department, Salary, Sal_cat]
Index: []

In [36]:
print(e[e['Salary']>mean+2*std]) #highest outliers

    Name  Age Department  Salary Sal_cat
4  Priya   27         HR  250000     low

# Advance Problems

In [37]:
cal=pd.read_csv('calendar.csv')
cust=pd.read_csv('customers.csv')
prod=pd.read_csv('products.csv')
sale=pd.read_csv('sales.csv')
store=pd.read_csv('stores.csv')

In [38]:
cal

           date  year  month  day  week  day_of_week
0    2023-01-01  2023      1    1    52            6
1    2023-01-02  2023      1    2     1            0
2    2023-01-03  2023      1    3     1            1
3    2023-01-04  2023      1    4     1            2
4    2023-01-05  2023      1    5     1            3
..          ...   ...    ...  ...   ...          ...
726  2024-12-27  2024     12   27    52            4
727  2024-12-28  2024     12   28    52            5
728  2024-12-29  2024     12   29    52            6
729  2024-12-30  2024     12   30     1            0
730  2024-12-31  2024     12   31     1            1

[731 rows x 6 columns]

In [39]:
prod

,product_id,product_name,brand,category,cocoa_percent,weight_g
0,P0001,White Chocolate 80%,Mars,Truffle,80,120
1,P0002,Dark Chocolate 70%,Cadbury,Praline,70,100
2,P0003,Truffle Chocolate 70%,Hershey,Praline,70,120
3,P0004,Milk Chocolate 50%,Mars,Praline,50,80
4,P0005,White Chocolate 70%,Ferrero,White,70,50
...,...,...,...,...,...,...
195,P0196,White Chocolate 60%,Mars,Praline,60,80
196,P0197,Truffle Chocolate 90%,Hershey,Truffle,90,120
197,P0198,Dark Chocolate 90%,Ferrero,White,90,80
198,P0199,Dark Chocolate 70%,Hershey,White,70,80
199,P0200,Milk Chocolate 50%,Cadbury,Milk,50,100

In [40]:
cust

      customer_id  age  gender  loyalty_member   join_date
0         C000001   40    Male               1  2025-05-21
1         C000002   47    Male               0  2021-12-26
2         C000003   58  Female               1  2022-09-13
3         C000004   25  Female               0  2025-02-27
4         C000005   43    Male               0  2023-08-31
...           ...  ...     ...             ...         ...
49995     C049996   30  Female               1  2022-11-21
49996     C049997   24  Female               0  2022-08-30
49997     C049998   53    Male               0  2024-09-22
49998     C049999   31  Female               1  2025-08-23
49999     C050000   39  Female               1  2023-12-02

[50000 rows x 5 columns]

In [41]:
sale

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40
...,...,...,...,...,...,...,...,...,...,...,...
999995,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,12.53
999996,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,4.37
999997,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,8.16
999998,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.00,4.90,2.56,2.34
999999,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,3.28

In [42]:
store

   store_id           store_name       city    country store_type
0      S001    Chocolate Store 1   New York     Canada     Retail
1      S002    Chocolate Store 2  Melbourne     Canada       Mall
2      S003    Chocolate Store 3     Berlin     France       Mall
3      S004    Chocolate Store 4      Paris         UK    Airport
4      S005    Chocolate Store 5     Sydney        USA     Online
..      ...                  ...        ...        ...        ...
95     S096   Chocolate Store 96     Berlin         UK       Mall
96     S097   Chocolate Store 97    Toronto     Canada       Mall
97     S098   Chocolate Store 98   New York  Australia     Online
98     S099   Chocolate Store 99    Toronto  Australia       Mall
99     S100  Chocolate Store 100     Berlin     France    Airport

[100 rows x 5 columns]

In [43]:
merged1=pd.merge(sale,store, on="store_id")
merged1

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit,store_name,city,country,store_type
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56,Chocolate Store 93,Sydney,UK,Airport
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97,Chocolate Store 65,New York,Australia,Retail
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75,Chocolate Store 78,London,UK,Airport
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04,Chocolate Store 88,Toronto,USA,Retail
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40,Chocolate Store 54,London,Canada,Online
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,12.53,Chocolate Store 53,New York,USA,Retail
999996,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,4.37,Chocolate Store 58,Paris,USA,Airport
999997,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,8.16,Chocolate Store 41,London,Germany,Airport
999998,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.00,4.90,2.56,2.34,Chocolate Store 83,Toronto,France,Mall
999999,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,3.28,Chocolate Store 90,Toronto,France,Online

In [44]:
print(merged1[merged1['city'].isna()])

Empty DataFrame
Columns: [order_id, order_date, product_id, store_id, customer_id, quantity, unit_price, discount, revenue, cost, profit, store_name, city, country, store_type]
Index: []

In [45]:
city_prof=merged1.groupby('city')['profit'].sum()
city_prof

city
Berlin       1024147.40
London       1622726.00
Melbourne    1223010.20
New York     1536934.11
Paris        1620456.75
Sydney       1330093.63
Toronto      1837196.54
Name: profit, dtype: float64

In [46]:
city_prof.head(5)

city
Berlin       1024147.40
London       1622726.00
Melbourne    1223010.20
New York     1536934.11
Paris        1620456.75
Name: profit, dtype: float64

In [47]:
merged1.groupby('store_type')['discount'].mean()

store_type
Airport    0.056162
Mall       0.056580
Online     0.056154
Retail     0.056052
Name: discount, dtype: float64

In [48]:
merged1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 15 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   order_id     1000000 non-null  object
 1   order_date   1000000 non-null  object
 2   product_id   1000000 non-null  object
 3   store_id     1000000 non-null  object
 4   customer_id  1000000 non-null  object
 5   quantity     1000000 non-null  int64
 6   unit_price   1000000 non-null  float64
 7   discount     1000000 non-null  float64
 8   revenue      1000000 non-null  float64
 9   cost         1000000 non-null  float64
 10  profit       1000000 non-null  float64
 11  store_name   1000000 non-null  object
 12  city         1000000 non-null  object
 13  country      1000000 non-null  object
 14  store_type   1000000 non-null  object
dtypes: float64(5), int64(1), object(9)
memory usage: 114.4+ MB

In [49]:
merged1['order_date']=pd.to_datetime(merged1['order_date'])

In [50]:
merged1['month']=merged1['order_date'].dt.month

In [51]:
merged1

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit,store_name,city,country,store_type,month
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56,Chocolate Store 93,Sydney,UK,Airport,1
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97,Chocolate Store 65,New York,Australia,Retail,10
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75,Chocolate Store 78,London,UK,Airport,5
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04,Chocolate Store 88,Toronto,USA,Retail,6
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40,Chocolate Store 54,London,Canada,Online,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,12.53,Chocolate Store 53,New York,USA,Retail,4
999996,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,4.37,Chocolate Store 58,Paris,USA,Airport,5
999997,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,8.16,Chocolate Store 41,London,Germany,Airport,7
999998,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.00,4.90,2.56,2.34,Chocolate Store 83,Toronto,France,Mall,1
999999,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,3.28,Chocolate Store 90,Toronto,France,Online,4

In [52]:
import numpy as np

In [53]:
merged1['is_high_margin']=np.where((merged1['profit']/merged1['revenue'])>0.30,'Yes','No')

In [54]:
merged1

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,profit,store_name,city,country,store_type,month,is_high_margin
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,18.56,Chocolate Store 93,Sydney,UK,Airport,1,Yes
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,16.97,Chocolate Store 65,New York,Australia,Retail,10,Yes
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,9.75,Chocolate Store 78,London,UK,Airport,5,Yes
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,10.04,Chocolate Store 88,Toronto,USA,Retail,6,Yes
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,4.40,Chocolate Store 54,London,Canada,Online,9,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,12.53,Chocolate Store 53,New York,USA,Retail,4,Yes
999996,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,4.37,Chocolate Store 58,Paris,USA,Airport,5,Yes
999997,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,8.16,Chocolate Store 41,London,Germany,Airport,7,Yes
999998,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.00,4.90,2.56,2.34,Chocolate Store 83,Toronto,France,Mall,1,Yes
999999,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,3.28,Chocolate Store 90,Toronto,France,Online,4,Yes

In [55]:
merged1.pivot_table(index='store_type',columns='is_high_margin',values='order_id',aggfunc='count')

is_high_margin   No     Yes
store_type
Airport         157  298962
Mall            131  259930
Online          110  250222
Retail           94  190394

In [56]:
df_final=pd.merge(merged1,prod, on="product_id")

In [57]:
df_final

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,...,city,country,store_type,month,is_high_margin,product_name,brand,category,cocoa_percent,weight_g
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,...,Sydney,UK,Airport,1,Yes,Praline Chocolate 70%,Hershey,White,70,200
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,...,New York,Australia,Retail,10,Yes,Dark Chocolate 60%,Lindt,Praline,60,50
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,...,London,UK,Airport,5,Yes,Milk Chocolate 90%,Hershey,Milk,90,50
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,...,Toronto,USA,Retail,6,Yes,Dark Chocolate 60%,Godiva,Praline,60,50
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,...,London,Canada,Online,9,Yes,Truffle Chocolate 90%,Hershey,Truffle,90,120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990231,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,...,New York,USA,Retail,4,Yes,Praline Chocolate 50%,Ferrero,White,50,100
990232,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,...,Paris,USA,Airport,5,Yes,Dark Chocolate 50%,Ferrero,Dark,50,200
990233,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,...,London,Germany,Airport,7,Yes,Milk Chocolate 80%,Godiva,Milk,80,50
990234,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.00,4.90,2.56,...,Toronto,France,Mall,1,Yes,Dark Chocolate 50%,Hershey,Praline,50,120
990235,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,...,Toronto,France,Online,4,Yes,White Chocolate 70%,Cadbury,Praline,70,100

In [58]:
print(df_final.groupby('product_name')[['revenue','quantity']].sum())

                          revenue  quantity
product_name
Dark Chocolate 50%     1775041.34    208996
Dark Chocolate 60%     1272649.97    149346
Dark Chocolate 70%     1017229.64    119825
Dark Chocolate 80%      634638.76     74734
Dark Chocolate 90%     1009248.87    118969
Milk Chocolate 50%     1014751.12    119141
Milk Chocolate 60%      883264.52    103564
Milk Chocolate 70%     1384758.27    162335
Milk Chocolate 80%      754675.84     88784
Milk Chocolate 90%      753459.18     88507
Praline Chocolate 50%  1382597.04    162670
Praline Chocolate 60%   497887.59     58771
Praline Chocolate 70%  1127404.94    132564
Praline Chocolate 80%   503618.28     59422
Praline Chocolate 90%   881139.19    103964
Truffle Chocolate 50%  1017102.43    120033
Truffle Chocolate 60%   377126.43     44244
Truffle Chocolate 70%   889254.20    104445
Truffle Chocolate 80%  1643258.83    193431
Truffle Chocolate 90%  1132883.80    133692
White Chocolate 50%    1265949.75    149170
White Chocolate 60%     750658.69     88704
White Chocolate 70%     998795.58    117771
White Chocolate 80%    1133285.39    133171
White Chocolate 90%    1137968.57    134217

In [59]:
df_final['is_discounted']=np.where(df_final['discount']>0,'Discounted','Full Price')

In [60]:
df_final

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,...,country,store_type,month,is_high_margin,product_name,brand,category,cocoa_percent,weight_g,is_discounted
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,...,UK,Airport,1,Yes,Praline Chocolate 70%,Hershey,White,70,200,Discounted
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,...,Australia,Retail,10,Yes,Dark Chocolate 60%,Lindt,Praline,60,50,Full Price
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,...,UK,Airport,5,Yes,Milk Chocolate 90%,Hershey,Milk,90,50,Full Price
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,...,USA,Retail,6,Yes,Dark Chocolate 60%,Godiva,Praline,60,50,Discounted
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,...,Canada,Online,9,Yes,Truffle Chocolate 90%,Hershey,Truffle,90,120,Full Price
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990231,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,...,USA,Retail,4,Yes,Praline Chocolate 50%,Ferrero,White,50,100,Full Price
990232,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,...,USA,Airport,5,Yes,Dark Chocolate 50%,Ferrero,Dark,50,200,Full Price
990233,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,...,Germany,Airport,7,Yes,Milk Chocolate 80%,Godiva,Milk,80,50,Full Price
990234,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.00,4.90,2.56,...,France,Mall,1,Yes,Dark Chocolate 50%,Hershey,Praline,50,120,Full Price
990235,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,...,France,Online,4,Yes,White Chocolate 70%,Cadbury,Praline,70,100,Discounted

In [61]:
g2=df_final.groupby('is_discounted')['quantity'].mean()

In [62]:
g2

is_discounted
Discounted    2.998173
Full Price    3.000711
Name: quantity, dtype: float64

In [68]:
top10=df_final.groupby('customer_id')['revenue'].sum()
print(top10.head(10))

customer_id
C000001    481.16
C000002    586.11
C000003    678.37
C000004    533.11
C000005    811.12
C000006    510.77
C000007    597.92
C000008    313.51
C000009    428.32
C000010    546.96
Name: revenue, dtype: float64

In [71]:
import numpy as np

df_final['ord_size_tag'] = df_final['quantity'].apply(
    lambda x: 'bulk' if x > 4 else ('standard' if x >= 2 else 'single')
)

In [72]:
df_final

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,...,store_type,month,is_high_margin,product_name,brand,category,cocoa_percent,weight_g,is_discounted,ord_size_tag
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,...,Airport,1,Yes,Praline Chocolate 70%,Hershey,White,70,200,Discounted,bulk
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,...,Retail,10,Yes,Dark Chocolate 60%,Lindt,Praline,60,50,Full Price,standard
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,...,Airport,5,Yes,Milk Chocolate 90%,Hershey,Milk,90,50,Full Price,standard
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,...,Retail,6,Yes,Dark Chocolate 60%,Godiva,Praline,60,50,Discounted,standard
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,...,Online,9,Yes,Truffle Chocolate 90%,Hershey,Truffle,90,120,Full Price,single
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990231,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,...,Retail,4,Yes,Praline Chocolate 50%,Ferrero,White,50,100,Full Price,standard
990232,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,...,Airport,5,Yes,Dark Chocolate 50%,Ferrero,Dark,50,200,Full Price,standard
990233,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,...,Airport,7,Yes,Milk Chocolate 80%,Godiva,Milk,80,50,Full Price,standard
990234,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.00,4.90,2.56,...,Mall,1,Yes,Dark Chocolate 50%,Hershey,Praline,50,120,Full Price,single
990235,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,...,Online,4,Yes,White Chocolate 70%,Cadbury,Praline,70,100,Discounted,single

In [83]:
df_final.pivot_table(index='category',columns='store_type',values='quantity',aggfunc='sum').style.background_gradient(axis=0)

In [90]:
# 1. Get total revenue per product and sort it
prod_rev = df_final.groupby('product_name')['revenue'].sum().sort_values(ascending=False)

# 2. Calculate the cumulative sum of revenue
cumulative_revenue = prod_rev.cumsum()

# 3. Calculate the total revenue of everything
total_rev_all = df_final['revenue'].sum()

# 4. Find how many products make up 50% of total revenue
half_revenue_mark = total_rev_all / 2
products_contributing_50 = cumulative_revenue[cumulative_revenue <= half_revenue_mark]

print(f"Total Products: {len(prod_rev)}")
print(f"Number of products contributing to 50% of revenue: {len(products_contributing_50)}")
print("\nTop 5 Revenue Drivers:")
print(prod_rev.head(5))

Total Products: 25
Number of products contributing to 50% of revenue: 9

Top 5 Revenue Drivers:
product_name
Dark Chocolate 50%       1775041.34
Truffle Chocolate 80%    1643258.83
Milk Chocolate 70%       1384758.27
Praline Chocolate 50%    1382597.04
Dark Chocolate 60%       1272649.97
Name: revenue, dtype: float64

In [94]:
# 1. Convert to datetime (just in case it isn't already)
df_final['order_date'] = pd.to_datetime(df_final['order_date'])

# 2. Create the 'day_of_week' column (0=Mon, 6=Sun)
df_final['day_of_week'] = df_final['order_date'].dt.dayofweek

# 3. Create 'is_weekend' using np.where
# 5 is Saturday, 6 is Sunday
df_final['is_weekend'] = np.where(df_final['day_of_week'] >= 5, 'Weekend', 'Weekday')

# 4. Group by your new column and find average revenue
weekend_analysis = df_final.groupby('is_weekend')['revenue'].mean()

print(weekend_analysis)

is_weekend
Weekday    25.502697
Weekend    25.449681
Name: revenue, dtype: float64

In [95]:
df_final

,order_id,order_date,product_id,store_id,customer_id,quantity,unit_price,discount,revenue,cost,...,is_high_margin,product_name,brand,category,cocoa_percent,weight_g,is_discounted,ord_size_tag,day_of_week,is_weekend
0,0RD00000001,2023-01-07,P0080,S093,C040749,5,14.43,0.15,61.33,42.77,...,Yes,Praline Chocolate 70%,Hershey,White,70,200,Discounted,bulk,5,Weekend
1,0RD00000002,2023-10-22,P0173,S065,C020161,3,12.01,0.00,36.03,19.06,...,Yes,Dark Chocolate 60%,Lindt,Praline,60,50,Full Price,standard,6,Weekend
2,0RD00000003,2023-05-07,P0115,S078,C048069,2,10.02,0.00,20.04,10.29,...,Yes,Milk Chocolate 90%,Hershey,Milk,90,50,Full Price,standard,6,Weekend
3,0RD00000004,2024-06-23,P0186,S088,C047901,2,14.66,0.10,26.39,16.35,...,Yes,Dark Chocolate 60%,Godiva,Praline,60,50,Discounted,standard,6,Weekend
4,0RD00000005,2024-09-24,P0197,S054,C033950,1,12.34,0.00,12.34,7.94,...,Yes,Truffle Chocolate 90%,Hershey,Truffle,90,120,Full Price,single,1,Weekday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990231,0RD00999996,2023-04-15,P0103,S053,C044763,4,7.45,0.00,29.80,17.27,...,Yes,Praline Chocolate 50%,Ferrero,White,50,100,Full Price,standard,5,Weekend
990232,0RD00999997,2023-05-26,P0094,S058,C004441,2,6.09,0.00,12.18,7.81,...,Yes,Dark Chocolate 50%,Ferrero,Dark,50,200,Full Price,standard,4,Weekday
990233,0RD00999998,2023-07-05,P0097,S041,C044879,3,6.09,0.00,18.27,10.11,...,Yes,Milk Chocolate 80%,Godiva,Milk,80,50,Full Price,standard,2,Weekday
990234,0RD00999999,2024-01-03,P0090,S083,C042525,1,4.90,0.00,4.90,2.56,...,Yes,Dark Chocolate 50%,Hershey,Praline,50,120,Full Price,single,2,Weekday
990235,0RD01000000,2024-04-10,P0175,S090,C025078,1,7.35,0.10,6.62,3.33,...,Yes,White Chocolate 70%,Cadbury,Praline,70,100,Discounted,single,2,Weekday