In [1]:
import pandas as pd

# Pandas series

In [2]:
sales=pd.Series([11,12,13,15,9,35,10])
print(sales[0])
print(sales[1:3])

11
1    12
2    13
dtype: int64

In [3]:
sales.index

RangeIndex(start=0, stop=7, step=1)

In [4]:
sales.dtype

dtype('int64')

In [5]:
sales.values

array([11, 12, 13, 15,  9, 35, 10])

In [6]:
sales.head(2)  #by default it shows 5 heads of series

0    11
1    12
dtype: int64

In [7]:
sales.head()

0    11
1    12
2    13
3    15
4     9
dtype: int64

In [8]:
sales.tail(2)  #by default it shows 5 tails of series

5    35
6    10
dtype: int64

In [9]:
sales.sort_values()

4     9
6    10
0    11
1    12
2    13
3    15
5    35
dtype: int64

In [10]:
ss=sales.sort_values()
l=[]
for sl in ss:
    l.append(sl)
l

[9, 10, 11, 12, 13, 15, 35]

In [11]:
sales.count()

np.int64(7)

In [12]:
sales.isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [13]:
sales.notnull()

0    True
1    True
2    True
3    True
4    True
5    True
6    True
dtype: bool

In [14]:
sales +10 #adds in all member

0    21
1    22
2    23
3    25
4    19
5    45
6    20
dtype: int64

In [15]:
sales *10

0    110
1    120
2    130
3    150
4     90
5    350
6    100
dtype: int64

In [16]:
t_sales=pd.Series([64,45,None,35,10])

In [17]:
t_sales.isnull()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [18]:
t_sales.notnull()

0     True
1     True
2    False
3     True
4     True
dtype: bool

In [19]:
t_sales.fillna(0) #to show null values filled

0    64.0
1    45.0
2     0.0
3    35.0
4    10.0
dtype: float64

In [20]:
t_sales  #it won't change permanently

0    64.0
1    45.0
2     NaN
3    35.0
4    10.0
dtype: float64

In [21]:
t_sales=t_sales.fillna(0) #reassign series
t_sales

0    64.0
1    45.0
2     0.0
3    35.0
4    10.0
dtype: float64

In [22]:
si=pd.Series(data=[100,200,303,505,449,135,210],index=list('abcdefg'))
si

a    100
b    200
c    303
d    505
e    449
f    135
g    210
dtype: int64

In [23]:
df=pd.DataFrame({'cust':['arun','dev'],
                'ods':[2,3]})

In [24]:
df

   cust  ods
0  arun    2
1   dev    3

In [25]:
s1=pd.Series(['a','b','c','d'])
s2=pd.Series([5,6,7,3,2])

In [26]:
sdf=pd.DataFrame({'col1':s1,'col2':s2})
sdf

  col1  col2
0    a     5
1    b     6
2    c     7
3    d     3
4  NaN     2

In [27]:
s1.shape #results in row,coloum

(4,)

In [28]:
sdf.shape

(5, 2)

In [29]:
sdf.columns

Index(['col1', 'col2'], dtype='object')

In [30]:
sdf.dtypes

col1    object
col2     int64
dtype: object

In [31]:
sdf['col2']

0    5
1    6
2    7
3    3
4    2
Name: col2, dtype: int64

In [32]:
sdf.loc[0,'col2'] #by label name

np.int64(5)

In [33]:
sdf.iloc[0,1] #by index

np.int64(5)

In [34]:
sdf.iloc[0]

col1    a
col2    5
Name: 0, dtype: object

In [35]:
sdf.iloc[2]

col1    c
col2    7
Name: 2, dtype: object

In [36]:
sdf.head()

  col1  col2
0    a     5
1    b     6
2    c     7
3    d     3
4  NaN     2

In [37]:
sdf.head(2)

  col1  col2
0    a     5
1    b     6

In [38]:
sdf.tail()

  col1  col2
0    a     5
1    b     6
2    c     7
3    d     3
4  NaN     2

In [39]:
sdf.tail(3)

  col1  col2
2    c     7
3    d     3
4  NaN     2

In [40]:
sdf.count()

col1    4
col2    5
dtype: int64

In [41]:
sdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col1    4 non-null      object
 1   col2    5 non-null      int64
dtypes: int64(1), object(1)
memory usage: 212.0+ bytes

In [42]:
sdf.describe() #describes numeric attributes

           col2
count  5.000000
mean   4.600000
std    2.073644
min    2.000000
25%    3.000000
50%    5.000000
75%    6.000000
max    7.000000

In [43]:
sdf.sort_values(by='col2')

  col1  col2
4  NaN     2
3    d     3
0    a     5
1    b     6
2    c     7

In [44]:
sdf.isnull()

    col1   col2
0  False  False
1  False  False
2  False  False
3  False  False
4   True  False

In [45]:
sdf.notnull()

    col1  col2
0   True  True
1   True  True
2   True  True
3   True  True
4  False  True

In [46]:
sdf[sdf['col2']>3]

  col1  col2
0    a     5
1    b     6
2    c     7

In [47]:
sdf[sdf['col1']=='d']

  col1  col2
3    d     3

In [48]:
sdf['col3']=[20,28,22,25,19] #adding new col

In [49]:
sdf

  col1  col2  col3
0    a     5    20
1    b     6    28
2    c     7    22
3    d     3    25
4  NaN     2    19

In [50]:
del sdf['col3']

In [51]:
sdf

  col1  col2
0    a     5
1    b     6
2    c     7
3    d     3
4  NaN     2

In [52]:
sdf['col3']=[20,28,22,25,19] #adding new col

In [53]:
sdf=sdf.drop(columns=['col2'])

In [54]:
sdf

  col1  col3
0    a    20
1    b    28
2    c    22
3    d    25
4  NaN    19

In [55]:
sdf=sdf.drop(4)

In [56]:
sdf

  col1  col3
0    a    20
1    b    28
2    c    22
3    d    25

In [57]:
sdf.loc[4] = [None, 17]  #adding new row

In [58]:
sdf

  col1  col3
0    a  20.0
1    b  28.0
2    c  22.0
3    d  25.0
4  NaN  17.0

In [59]:
sdf.loc[sdf['col3']==22, 'col3']=40   #update

In [60]:
sdf

  col1  col3
0    a  20.0
1    b  28.0
2    c  40.0
3    d  25.0
4  NaN  17.0

In [61]:
sdf.rename(columns={'col1':'c1','col3':'c2'})  #temp rename

    c1    c2
0    a  20.0
1    b  28.0
2    c  40.0
3    d  25.0
4  NaN  17.0

In [62]:
sdf.rename(columns={'col1':'c1','col3':'c2'}, inplace=True)  #permanent rename

In [63]:
sdf

    c1    c2
0    a  20.0
1    b  28.0
2    c  40.0
3    d  25.0
4  NaN  17.0

In [64]:
df=pd.DataFrame({'id':[1001,1002,1003,1004],'name':['Arun','Ashok','Raz','Vivek'],'sal':[20000,30000,21000,16000]})

In [65]:
df

     id   name    sal
0  1001   Arun  20000
1  1002  Ashok  30000
2  1003    Raz  21000
3  1004  Vivek  16000

In [66]:
df.set_index('id',inplace=True)  #id col becames index

In [67]:
df

       name    sal
id
1001   Arun  20000
1002  Ashok  30000
1003    Raz  21000
1004  Vivek  16000

In [68]:
df.loc[1001,'name']

'Arun'

In [69]:
df.reset_index(inplace=True)

In [70]:
df

     id   name    sal
0  1001   Arun  20000
1  1002  Ashok  30000
2  1003    Raz  21000
3  1004  Vivek  16000

In [71]:
mdf=pd.DataFrame({'ch':['a','a','b','b'], 'id':[11,12,13,14], 'nm':['rx','ze','li','fe']}).set_index(['ch','id'])

In [72]:
mdf

       nm
ch id
a  11  rx
   12  ze
b  13  li
   14  fe

In [73]:
mdf[mdf['nm']=='ze']  #conditional

       nm
ch id
a  12  ze

In [74]:
df

     id   name    sal
0  1001   Arun  20000
1  1002  Ashok  30000
2  1003    Raz  21000
3  1004  Vivek  16000

In [75]:
df.query('sal>20000')   #short conditional

     id   name    sal
1  1002  Ashok  30000
2  1003    Raz  21000

In [76]:
# df.to_csv('a1.csv',index=False)

In [77]:
# df1=pd.read_csv('a1.csv')

In [78]:
# df1

In [79]:
# df1=df1.drop(columns=['index']

In [80]:
#df1

In [81]:
import numpy as np
dict={'x':[11,12,13],'y':np.array([100,200,300]),'z':50}

In [82]:
df11=pd.DataFrame(dict)

In [83]:
df11

    x    y   z
0  11  100  50
1  12  200  50
2  13  300  50

In [84]:
list=[[1,2,3],[4,5,6],[7,8,9]]

In [85]:
df12=pd.DataFrame(list)

In [86]:
df12

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [87]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [88]:
df13=pd.DataFrame(arr)

In [89]:
df13

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [90]:
sdf

    c1    c2
0    a  20.0
1    b  28.0
2    c  40.0
3    d  25.0
4  NaN  17.0

In [91]:
sdf.fillna(1) 
# sdf.fillna(sdf.mean)

  c1    c2
0  a  20.0
1  b  28.0
2  c  40.0
3  d  25.0
4  1  17.0

In [92]:
sdf.dropna()

  c1    c2
0  a  20.0
1  b  28.0
2  c  40.0
3  d  25.0

In [93]:
ddf=pd.DataFrame({'x':[100,100,100,100,100], 'y':[500,500,200,500,100]})

In [94]:
ddf

     x    y
0  100  500
1  100  500
2  100  200
3  100  500
4  100  100

In [95]:
ddf.drop_duplicates() #removes all repeated rows, stay one only

     x    y
0  100  500
2  100  200
4  100  100

In [96]:
ddf

     x    y
0  100  500
1  100  500
2  100  200
3  100  500
4  100  100

In [97]:
ddf.replace(100,11)

    x    y
0  11  500
1  11  500
2  11  200
3  11  500
4  11   11

In [98]:
ddf['x']=ddf['x'].astype(float)

In [99]:
ddf

       x    y
0  100.0  500
1  100.0  500
2  100.0  200
3  100.0  500
4  100.0  100

In [100]:
ddf['x']=ddf['x'].astype(int)

In [101]:
ddf['cust']=["Arun", "Raz","Dev","Deep","rahul"]

In [102]:
ddf

     x    y   cust
0  100  500   Arun
1  100  500    Raz
2  100  200    Dev
3  100  500   Deep
4  100  100  rahul

In [103]:
ddf['cust'].str.upper()  #string uppercase/lowercase

0     ARUN
1      RAZ
2      DEV
3     DEEP
4    RAHUL
Name: cust, dtype: object

In [104]:
sh1=pd.DataFrame({'name':['a','b','c','a','a','c','b'],'qnt':[2,3,4,3,2,1,2],'amt':[20,30,40,20,20,10,20]})

In [105]:
sh1

  name  qnt  amt
0    a    2   20
1    b    3   30
2    c    4   40
3    a    3   20
4    a    2   20
5    c    1   10
6    b    2   20

In [106]:
grouped1=sh1.groupby('name')

In [107]:
grouped1.sum()

      qnt  amt
name
a       7   60
b       5   50
c       5   50

In [108]:
grouped1.max()

      qnt  amt
name
a       3   20
b       3   30
c       4   40

In [109]:
grouped1.min()

      qnt  amt
name
a       2   20
b       2   20
c       1   10

In [110]:
grouped1.mean()

           qnt   amt
name
a     2.333333  20.0
b     2.500000  25.0
c     2.500000  25.0

In [111]:
sh1.pivot_table(index=['name'],values=['amt'])  # same as mean

       amt
name
a     20.0
b     25.0
c     25.0

In [112]:
pd.crosstab(sh1['name'],sh1['qnt'])   #counts how many time another value represnted for their respective column

qnt   1  2  3  4
name
a     0  2  1  0
b     0  1  1  0
c     1  0  0  1

In [113]:
d1=pd.DataFrame({'name':['a','i','e','o','u'],'data':[52,15,23,39,18]})
d2=pd.DataFrame({'name':['a','b','c','d','e'],'num':[10,20,30,40,50]})

In [114]:
d1

  name  data
0    a    52
1    i    15
2    e    23
3    o    39
4    u    18

In [115]:
d2

  name  num
0    a   10
1    b   20
2    c   30
3    d   40
4    e   50

In [116]:
pd.concat([d1,d2])

  name  data   num
0    a  52.0   NaN
1    i  15.0   NaN
2    e  23.0   NaN
3    o  39.0   NaN
4    u  18.0   NaN
0    a   NaN  10.0
1    b   NaN  20.0
2    c   NaN  30.0
3    d   NaN  40.0
4    e   NaN  50.0

In [117]:
pd.merge(d1,d2)

  name  data  num
0    a    52   10
1    e    23   50

In [118]:
pd.merge(d1,d2, on='name')

  name  data  num
0    a    52   10
1    e    23   50

In [119]:
d1.join(d2.set_index('name'),on='name')

  name  data   num
0    a    52  10.0
1    i    15   NaN
2    e    23  50.0
3    o    39   NaN
4    u    18   NaN

In [120]:
d1['date']=['22-12-2000','2005-06-30','2011-01-19','12-07-2010','2009-12-12']

In [121]:
d1

  name  data        date
0    a    52  22-12-2000
1    i    15  2005-06-30
2    e    23  2011-01-19
3    o    39  12-07-2010
4    u    18  2009-12-12

In [122]:
d1['date']=pd.to_datetime(d1['date'], format='mixed', dayfirst=True)  #to format dates

In [123]:
d1

  name  data       date
0    a    52 2000-12-22
1    i    15 2005-06-30
2    e    23 2011-01-19
3    o    39 2010-07-12
4    u    18 2009-12-12

In [124]:
d1.reset_index(inplace=True)

In [125]:
d1.set_index('date',inplace=True)

In [126]:
d1

            index name  data
date
2000-12-22      0    a    52
2005-06-30      1    i    15
2011-01-19      2    e    23
2010-07-12      3    o    39
2009-12-12      4    u    18

In [127]:
d1.resample('MS').sum() #month starting

            index name  data
date
2000-12-01      0    a    52
2001-01-01      0    0     0
2001-02-01      0    0     0
2001-03-01      0    0     0
2001-04-01      0    0     0
...           ...  ...   ...
2010-09-01      0    0     0
2010-10-01      0    0     0
2010-11-01      0    0     0
2010-12-01      0    0     0
2011-01-01      2    e    23

[122 rows x 3 columns]

In [128]:
d1.resample('ME').sum() #month ending

            index name  data
date
2000-12-31      0    a    52
2001-01-31      0    0     0
2001-02-28      0    0     0
2001-03-31      0    0     0
2001-04-30      0    0     0
...           ...  ...   ...
2010-09-30      0    0     0
2010-10-31      0    0     0
2010-11-30      0    0     0
2010-12-31      0    0     0
2011-01-31      2    e    23

[122 rows x 3 columns]

In [129]:
d1.resample('W').sum() #weekly

            index name  data
date
2000-12-24      0    a    52
2000-12-31      0    0     0
2001-01-07      0    0     0
2001-01-14      0    0     0
2001-01-21      0    0     0
...           ...  ...   ...
2010-12-26      0    0     0
2011-01-02      0    0     0
2011-01-09      0    0     0
2011-01-16      0    0     0
2011-01-23      2    e    23

[527 rows x 3 columns]

In [130]:
d1.resample('YE').sum() #yearly ending

            index name  data
date
2000-12-31      0    a    52
2001-12-31      0    0     0
2002-12-31      0    0     0
2003-12-31      0    0     0
2004-12-31      0    0     0
2005-12-31      1    i    15
2006-12-31      0    0     0
2007-12-31      0    0     0
2008-12-31      0    0     0
2009-12-31      4    u    18
2010-12-31      3    o    39
2011-12-31      2    e    23

In [131]:
d1.resample('YS').sum()

            index name  data
date
2000-01-01      0    a    52
2001-01-01      0    0     0
2002-01-01      0    0     0
2003-01-01      0    0     0
2004-01-01      0    0     0
2005-01-01      1    i    15
2006-01-01      0    0     0
2007-01-01      0    0     0
2008-01-01      0    0     0
2009-01-01      4    u    18
2010-01-01      3    o    39
2011-01-01      2    e    23

In [132]:
d1['temp_data']=d1['data'].shift(2)  #adds  2 NaN in starting of data

In [133]:
d1

            index name  data  temp_data
date
2000-12-22      0    a    52        NaN
2005-06-30      1    i    15        NaN
2011-01-19      2    e    23       52.0
2010-07-12      3    o    39       15.0
2009-12-12      4    u    18       23.0

In [134]:
d1['rolling_avg']=d1['data'].rolling(window=2).mean()   #n-1 will be NaN values

In [135]:
d1

            index name  data  temp_data  rolling_avg
date
2000-12-22      0    a    52        NaN          NaN
2005-06-30      1    i    15        NaN         33.5
2011-01-19      2    e    23       52.0         19.0
2010-07-12      3    o    39       15.0         31.0
2009-12-12      4    u    18       23.0         28.5